spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coffee?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 1314DestinyStone
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9999
